--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MulqiGaming64/LibYoutubeDetail
build-by-default: true
branches:
- main
projects:
  LibYoutubeDetail:
    path: ""
    model: virion
    type: library
...
